# data_path = r"Datasets\flight_data.csv"
# data_path = r"Datasets/data_whole.parquet"
data_path = r"Datasets/circle_id3.parquet"
# data_path = r"Datasets/surbhi.csv"
problem_type = "regression"  #"""classification"""
kind = "load_forecasting2" #"flight"
